import BlockPage from "@/components/BlockPage";
import { Router, Cpu, Home, Factory, ShieldAlert } from "lucide-react";

export default function IoTSecurity() {
  return (
    <BlockPage
      title="IoT Security"
      subtitle="Segurança de dispositivos conectados"
      icon={Router}
      description="A Internet of Things (IoT) conecta milhares de milhões de dispositivos — câmaras, sensores, eletrodomésticos, dispositivos médicos, sistemas industriais. Muitos destes dispositivos têm segurança fraca: passwords por defeito, sem atualizações e comunicações não encriptadas. IoT Security trata de proteger este ecossistema crescente."
      audience="Utilizadores de dispositivos smart home, profissionais de TI em ambientes industriais, gestores de infraestruturas e qualquer pessoa com dispositivos IoT em casa."
      connections="Liga-se a Foundations (redes), Cloud Security (dados IoT na cloud), Vulnerability Management (firmware desatualizado) e Privacy Engineering (dados pessoais recolhidos por IoT)."
      subtopics={[
        { title: "Smart Home Security", icon: Home, explanation: "Câmaras de vigilância, assistentes de voz, lâmpadas inteligentes, fechaduras smart — todos se ligam à tua rede Wi-Fi. Se um dispositivo IoT for comprometido, pode servir de porta de entrada para toda a rede doméstica. Muitos dispositivos IoT usam passwords por defeito (admin/admin) e nunca recebem atualizações de segurança.", importance: "Um dispositivo IoT comprometido pode espiar-te (câmaras/microfones), dar acesso à tua rede ou ser usado em ataques a outros (botnets).", realExample: "O botnet Mirai (2016) infetou centenas de milhares de dispositivos IoT com passwords por defeito e usou-os para lançar o maior ataque DDoS da história, derrubando serviços como Twitter, Netflix e Reddit.", practicalTask: "Faz uma auditoria IoT em casa: lista todos os dispositivos ligados ao teu Wi-Fi (router, TV, câmaras, assistentes, etc.). Para cada um, verifica: a password foi alterada do defeito? O firmware está atualizado? Precisa mesmo de estar ligado à internet?", bestPractices: ["Muda SEMPRE as passwords por defeito em dispositivos IoT.", "Cria uma rede Wi-Fi separada para dispositivos IoT.", "Desativa funcionalidades que não usas (UPnP, acesso remoto).", "Verifica atualizações de firmware regularmente."] },
        { title: "Segurança Industrial (ICS/SCADA)", icon: Factory, explanation: "ICS (Industrial Control Systems) e SCADA (Supervisory Control and Data Acquisition) controlam infraestruturas críticas: centrais elétricas, redes de água, fábricas, transportes. Estes sistemas foram desenhados para funcionar isolados, mas estão cada vez mais ligados à internet — criando riscos enormes.", importance: "Um ataque a sistemas industriais pode ter consequências físicas: cortes de eletricidade, contaminação de água, acidentes industriais. Não é apenas informação em risco — são vidas.", realExample: "O Stuxnet (2010) foi o primeiro malware desenhado para atacar sistemas industriais. Destruiu centenas de centrifugadoras nucleares no Irão, alterando silenciosamente a velocidade de rotação enquanto mostrava valores normais aos operadores.", practicalTask: "Pensa em infraestruturas que usas diariamente: eletricidade, água, transportes. Todas são controladas por sistemas digitais. Se um atacante controlasse o semáforo de um cruzamento movimentado, ou a dosagem de cloro numa estação de tratamento de água, o impacto seria físico e imediato.", bestPractices: ["Segmenta redes industriais da rede corporativa e da internet.", "Monitoriza comunicações anómalas em redes ICS.", "Mantém inventário de todos os dispositivos e versões de firmware.", "Implementa autenticação forte para acesso a sistemas de controlo."] },
        { title: "Firmware e Atualizações", icon: Cpu, explanation: "Firmware é o software embebido em dispositivos IoT. Ao contrário de apps no telemóvel, o firmware raramente se atualiza automaticamente. Muitos fabricantes deixam de lançar atualizações após alguns anos, deixando dispositivos permanentemente vulneráveis. Analisar firmware pode revelar passwords hardcoded, backdoors e vulnerabilidades conhecidas.", importance: "Um dispositivo IoT sem atualizações é como um computador com Windows XP ligado à internet — é uma questão de tempo até ser comprometido.", realExample: "Investigadores analisaram o firmware de routers populares e encontraram credenciais hardcoded (username e password escritos diretamente no código), backdoors de administração e chaves de encriptação partilhadas entre todos os dispositivos do mesmo modelo.", practicalTask: "Verifica o teu router doméstico: acede ao painel de administração (geralmente 192.168.1.1 ou 192.168.0.1) e verifica a versão de firmware. Pesquisa no site do fabricante se há atualizações disponíveis. Se o router tem mais de 5 anos e não recebe atualizações, considera substituí-lo.", bestPractices: ["Verifica atualizações de firmware pelo menos trimestralmente.", "Antes de comprar dispositivos IoT, verifica se o fabricante lança atualizações regulares.", "Substitui dispositivos que já não recebem suporte do fabricante.", "Desativa serviços desnecessários e portas abertas em dispositivos IoT."] },
        { title: "Protocolo e Comunicações IoT", icon: ShieldAlert, explanation: "Dispositivos IoT usam protocolos de comunicação variados: MQTT, CoAP, Zigbee, Z-Wave, Bluetooth LE. Muitos destes protocolos foram desenhados para eficiência energética, não para segurança. Comunicações sem encriptação permitem que atacantes interceptem dados ou enviem comandos falsos a dispositivos.", importance: "Se as comunicações IoT não são encriptadas, um atacante na mesma rede pode ver dados de sensores, abrir fechaduras smart ou desativar alarmes.", realExample: "Investigadores demonstraram que podiam interceptar comunicações Zigbee de lâmpadas inteligentes e usar esse acesso para se mover lateralmente na rede, chegando eventualmente a dispositivos mais sensíveis como computadores e NAS.", practicalTask: "Se tens dispositivos Bluetooth em casa (colunas, headphones, smartwatch), verifica se usam Bluetooth LE com pairing seguro. Desativa o Bluetooth quando não estiver em uso — reduz a superfície de ataque do teu telemóvel.", bestPractices: ["Usa protocolos IoT com encriptação sempre que possível.", "Segmenta dispositivos IoT numa VLAN dedicada.", "Monitoriza tráfego IoT para detetar anomalias.", "Desativa protocolos de comunicação quando não estão em uso."] },
      ]}
      tools={[
        { name: "Shodan", url: "https://www.shodan.io", desc: "Motor de pesquisa de dispositivos IoT expostos" },
        { name: "Firmware Analysis Toolkit", url: "https://github.com/ReFirmLabs/binwalk", desc: "Análise e extração de firmware" },
        { name: "EMBA", url: "https://github.com/e-m-b-a/emba", desc: "Scanner de segurança de firmware" },
      ]}
      websites={[
        { name: "OWASP IoT", url: "https://owasp.org/www-project-internet-of-things", desc: "Projeto OWASP de segurança IoT" },
        { name: "ICS-CERT", url: "https://www.cisa.gov/topics/industrial-control-systems", desc: "Alertas de segurança para sistemas industriais" },
        { name: "IoT Security Foundation", url: "https://www.iotsecurityfoundation.org", desc: "Boas práticas de segurança IoT" },
      ]}
      relatedAreas={[
        { title: "Cloud Security", url: "/cloud-security", desc: "Dados IoT na cloud" },
        { title: "Foundations", url: "/foundations", desc: "Redes e protocolos base" },
        { title: "Vulnerability Management", url: "/vulnerability-management", desc: "Gestão de vulnerabilidades em firmware" },
      ]}
    />
  );
}
